"""change post table

Revision ID: c13f2665862d
Revises: 3dce6c639084
Create Date: 2019-11-21 13:20:59.154588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13f2665862d'
down_revision = '3dce6c639084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('ix_post_timestmp', table_name='post')
    op.drop_column('post', 'timestmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestmp', sa.DATETIME(), nullable=True))
    op.create_index('ix_post_timestmp', 'post', ['timestmp'], unique=False)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
